sudo: required

language: python

services:
  - docker

env:
  global:
    - DOCKER_REPO="laslabs/clouder-python-exec"
    - BRANCH_PROD="master"
  matrix:
    - TESTS="1" PYTHON_VERSION="3" BUILD_ARGS='PYTHON_PACKAGE="python3"'
    - TESTS="1" PYTHON_VERSION="2" BUILD_ARGS='PYTHON_PACKAGE="python"'
    - LINT_CHECK="1"
    - HUB="1" PYTHON_VERSION="3" BUILD_ARGS='PYTHON_PACKAGE="python3"'
    - HUB="1" PYTHON_VERSION="2" BUILD_ARGS='PYTHON_PACKAGE="python"'

install:
  - git clone --depth=1 https://github.com/LasLabs/docker-quality-tools.git ${HOME}/docker-quality-tools
  - export PATH=${HOME}/docker-quality-tools/travis:${PATH}
  - travis_install_all

script:
  - travis_run_all

after_success:
  - travis_after_success_all
